

services:
  postgres:
    image: postgres:15-alpine
    container_name: ${POSTGRES_CONTAINER_NAME:-legal_simplifier}
    restart: unless-stopped
    env_file: ./.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: "UTC"
    ports:
      - "${POSTGRES_PORT:-5430}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./Backend
    container_name: legal_backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    env_file: ./.env
    environment:
      - GOOGLE_CLOUD_PROJECT_ID=gen-ai-hackathon-471308
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    volumes:
      - /home/sachin2089/documet_analyzer/Gen_AI_Hackathon/Backend/keys/gen-ai-hackathon-471308-d75b11abf148.json:/app/keys/gen-ai-hackathon-471308-bbadeb147ac0.json  # mount your credentials

  streamlit:
    build: ./Frontend
    container_name: legal_streamlit
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - API_BASE=http://backend:8080
    volumes:
      - ./Frontend:/app

volumes:
  postgres_data:
